### ISSUE TITLE
Visual Studio for Mac hides part of the deployment target in the UI

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/NetMF_MonoDevelop_VS_Mac_Addin#11]
looks like this:

<img width="303" alt="screen shot 2018-01-14 at 6 15 46 pm" src="https://user-images.githubusercontent.com/947633/34924257-31ac6c26-f957-11e7-8332-9458b54d8b0c.png">

**Comment by chkn** [comment]
I think this is already fixed: https://github.com/mono/monodevelop/pull/3626

**Comment by bryancostanich** [comment]
oh yeah.
